import test from 'node:test';import assert from 'node:assert/strict';import {purchaseImportStep} from '../tools/fleamarket-extension/purchase-import.js';
const a={site:'mercari',label:'メルカリ1',listUrl:'https://jp.mercari.com/mypage/purchases',identity:{text:'本人'}};
const row=(id,date='2026-10-01')=>({marketplace_item_id:id,marketplace_url:'https://jp.mercari.com/item/'+id,detailUrl:'https://jp.mercari.com/transaction/'+id,purchased_at:date,title:'SONY ABC-123',cost_amount:1200});
function setup(rows,known=[]){const calls=[],reads=[],tasks=[];let finished=0;const j={kind:'purchases',stage:'purchase-context',counts:{checked:0,imported:0,skipped:0,errors:0},seenPages:[]};const s={dbSite:'メルカリ',verifyAccount:async()=>{},navigate:async()=>{},save:async()=>{},nextAccount:async()=>{finished++;},log:async()=>{},task:async(...x)=>tasks.push(x),rpc:async(name,args)=>{calls.push({name,args});return name==='marketplace_purchase_context'?{day:'2026-10-07',cutoff:'2026-09-07',knownIds:known}:{inserted:1,rejected:0,skipped:0};},read:async(id,type)=>{reads.push(type);return type==='list'?{purchaseRows:rows,emptyConfirmed:!rows.length}:type==='purchaseMore'?{endConfirmed:true}:{purchased_at:null,cost_amount:null};}};return {j,s,calls,reads,tasks,finished:()=>finished};}
test('在庫一致で終了せずその先の未登録だけ追加、古い商品と重複は詳細を開かない',async()=>{const x=setup([row('m1'),row('m2'),row('m3','2026-08-01')],['m1']);for(let n=0;n<5&&!x.finished();n++)await purchaseImportStep(x.j,a,x.s);assert.equal(x.j.counts.imported,1);assert.equal(x.calls.filter(c=>c.name==='marketplace_purchase_import')[0].args.p_purchases[0].marketplace_item_id,'m2');assert.equal(x.reads.includes('purchaseDetail'),false);assert.equal(x.finished(),1);});
test('名前不一致では購入一覧を読み取らず保存しない',async()=>{const x=setup([row('m1')]);x.s.verifyAccount=async()=>{throw Error('名前不一致');};await assert.rejects(purchaseImportStep(x.j,a,x.s),/名前不一致/);assert.equal(x.reads.length,0);assert.equal(x.calls.length,1);});
test('購入日不明は詳細でも確認できなければタスクにし、保存しない',async()=>{const x=setup([row('m1',null)]);for(let n=0;n<3;n++)await purchaseImportStep(x.j,a,x.s);assert.equal(x.j.counts.imported,0);assert.equal(x.tasks.length,1);assert.equal(x.reads.includes('purchaseDetail'),true);assert.equal(x.calls.some(c=>c.name==='marketplace_purchase_import'),false);});
test('金額不明は詳細確認後も推測せずnullのまま下書きに保存',async()=>{const r=row('m1');r.cost_amount=null;const x=setup([r]);for(let n=0;n<3;n++)await purchaseImportStep(x.j,a,x.s);assert.equal(x.calls.at(-1).args.p_purchases[0].cost_amount,null);assert.equal(x.j.counts.imported,1);});
test('キャンセル済みは追加せず、空一覧は正常終了',async()=>{for(const rows of [[],[{...row('m1'),cancelled:true}]]){const x=setup(rows);for(let n=0;n<4&&!x.finished();n++)await purchaseImportStep(x.j,a,x.s);assert.equal(x.j.counts.imported,0);assert.equal(x.finished(),1);}});

test('同じサイトの他アカウントが巡回中は一覧へアクセスせず待ち、取得権限が取れたら進む',async()=>{const x=setup([row('m1')]);let held=false;x.s.lease=async()=>held;await purchaseImportStep(x.j,a,x.s);assert.equal(x.j.stage,'purchase-context');assert.equal(x.calls.length,0);assert.equal(x.reads.length,0);held=true;await purchaseImportStep(x.j,a,x.s);assert.equal(x.j.stage,'purchase-list');});
